services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulk-insert-api
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "rahulbp"
    restart: always
    env_file:
      - .env
    networks:
      - bulk-insert-network
    volumes:
      - /uploads
    command: sh -c "npm run dev"
    profiles:
      - prod
  
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bulk-insert-dev-api
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "rahulbp"
    restart: always
    env_file:
      - .env
    networks:
      - bulk-insert-dev-network
    volumes:
      - /uploads
    command: sh -c "npm run dev"
    profiles:
      - dev

  redis:
    image: redis:8.6-alpine
    container_name: bulk-insert-redis
    hostname: redis
    networks:
      - bulk-insert-network
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - prod

  redis-dev:
    image: redis:8-alpine
    container_name: bulk-insert-redis-dev
    hostname: redis-dev
    restart: unless-stopped
    networks:
      - bulk-insert-dev-network
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data_dev:/data
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - dev


networks:
  bulk-insert-dev-network:
    driver: bridge
  bulk-insert-network:
    driver: bridge

volumes:
  uploads:
  redis_data:
  redis_data_dev:
